version: '3.8'
services:
  db:
    image: postgres:13
    container_name: blokdeprem-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blokdeprem
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  ai-service:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: blokdeprem-ai
    ports:
      - "5000:5000"
    volumes:
      - ./ai:/app


volumes:
  postgres_data:
